// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7xcijrttpSq-it1-QBCpav4qXZcTiKQ',
    appId: '1:644621164238:web:cc815f60a053cf24bbba9f',
    messagingSenderId: '644621164238',
    projectId: 'store-134b5',
    authDomain: 'store-134b5.firebaseapp.com',
    storageBucket: 'store-134b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLO_qaNemHLsoZqczcjE7o_eVMc-1PwkI',
    appId: '1:644621164238:android:d78782436d310d3cbbba9f',
    messagingSenderId: '644621164238',
    projectId: 'store-134b5',
    storageBucket: 'store-134b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHrDwdesJ5Dmji6BaP9qQHVOpihmcYv2M',
    appId: '1:644621164238:ios:477d6a5e8595cf3bbbba9f',
    messagingSenderId: '644621164238',
    projectId: 'store-134b5',
    storageBucket: 'store-134b5.appspot.com',
    iosClientId: '644621164238-hcvot3k5ls3eo9oje8jcss37ul1nerfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.vapeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHrDwdesJ5Dmji6BaP9qQHVOpihmcYv2M',
    appId: '1:644621164238:ios:477d6a5e8595cf3bbbba9f',
    messagingSenderId: '644621164238',
    projectId: 'store-134b5',
    storageBucket: 'store-134b5.appspot.com',
    iosClientId: '644621164238-hcvot3k5ls3eo9oje8jcss37ul1nerfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.vapeApp',
  );
}
